### ISSUE TITLE
Drop uni namespace from names.

### ISSUE THREAD

**Issue by atilkan** [antonreshetov/vue-unicons#20]
uni namespace at the beginning is not really a necessary. It makes it hard to type and read. And import and usage names are also different.

**Comment by antonreshetov** [comment]
If you get to the bottom of this, you'll understand why a prefix is needed

**Comment by atilkan** [comment]
I read the source and i still think the same. What was the reason? 
Let me understand.

**Comment by antonreshetov** [comment]
https://github.com/antonreshetov/vue-unicons/blob/master/src/icons.js#L867
In javascript there are reserved names. And `export` one of them.

In the future, some of the new icon names may overlap with these names.

But even assuming there's no such problem. I still don't see what your problem is to start typing "uni", especially since there is such a thing as an autocomplet.

**Comment by atilkan** [comment]
Yep i checked. And i still think the same. If you drop uni, all will still work. 
For autocomplete to start working i have to type 4 chars. It is ironic how you wrote **autocomplet**.
Actually, i used this plugin before, after a while i exported all and mapped. This made a very heavy export. 
I hated typing those 4 character every time i wrote with a passion.

**Comment by atilkan** [comment]
@antonreshetov So i know i have a valid point here. Will you ignore it?

**Comment by antonreshetov** [comment]
I think you still don't understand the problem. Please let's stop the discussion about this. You can make a fork, and do whatever you want to do there. It's an opensorce.
